#!/usr/bin/env bash
rm -rf dist
mkdir -p dist
echo "build src/ldld.ls -> dist/index.js ..."
./node_modules/.bin/lsc -cp --no-header src/ldld.ls > dist/index.js
echo "build src/ldld.styl -> dist/index.css ..."
./node_modules/.bin/stylus -p src/ldld.styl > dist/index.css
echo "minifying index.js ..."
./node_modules/.bin/uglifyjs dist/index.js -m -c > dist/index.min.js
echo "minifying index.css ..."
./node_modules/.bin/uglifycss dist/index.css > dist/index.min.css
echo "done."
echo "Copy dist/ to web/ ..."
rm -rf web/static/assets/lib/ldloader/dev/
mkdir -p web/static/assets/lib/ldloader/dev/
cp -R dist/* web/static/assets/lib/ldloader/dev/
echo "done."

