#!/usr/bin/env bash
rm -rf dist
mkdir -p dist
echo "build src/ldld.ls -> dist/ldld.js ..."
./node_modules/.bin/lsc -cp --no-header src/ldld.ls > dist/ldld.js
echo "build src/ldld.styl -> dist/ldld.css ..."
./node_modules/.bin/stylus -p src/ldld.styl > dist/ldld.css
echo "minifying ldld.js ..."
./node_modules/.bin/uglifyjs dist/ldld.js > dist/ldld.min.js
echo "minifying ldld.css ..."
./node_modules/.bin/uglifycss dist/ldld.css > dist/ldld.min.css
echo "done."

