// Generated by LiveScript 1.3.1
var ldld, show, btnTest, f;
ldld = {};
['full', 'default', 'btn'].map(function(it){
  return ldld[it] = new ldLoader({
    root: ".test." + it
  });
});
ldld.ctrl = new ldLoader({
  root: ".test.ctrl",
  ctrl: {
    step: function(t){
      return this.innerText = Math.round(t / 100) / 10 + "s passed.";
    },
    done: function(t){
      return this.innerText = "Finished.";
    }
  }
});
show = function(name){
  ldld[name].on();
  return ldld[name].off(2000);
};
btnTest = document.querySelector('.btn-test');
f = function(t){
  var x;
  requestAnimationFrame(f);
  x = Math.round(Math.sin(t * 0.001) * 300);
  return btnTest.style.left = x + "px";
};
requestAnimationFrame(f);