// Generated by LiveScript 1.3.1
var ldcv, show;
ldcv = new ldCover({
  root: document.querySelector('.ldcv')
});
ldcv.toggle(false);
show = function(){
  return ldcv.get().then(function(it){
    return console.log('ok', it);
  });
};